name: Zazeni orv

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.1'

    - name: Log in to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        # Build the Docker image with a tag based on the Git commit SHA
        docker build -t ${{ secrets.DOCKER_USERNAME }}/orv:${{ github.sha }} .
        # Push the image to Docker Hub
        docker push ${{ secrets.DOCKER_USERNAME }}/orv:${{ github.sha }}

    - name: Stop existing containers on port 3000
      run: |
        # Find containers using port 3000 and stop them
        docker ps -q --filter "expose=3000" | xargs -r docker stop
        docker ps -aq --filter "expose=3000" | xargs -r docker rm

    - name: Deploy
      run: |
        # Pull the latest image using the commit SHA to ensure the latest version is deployed
        docker pull ${{ secrets.DOCKER_USERNAME }}/orv:${{ github.sha }}
        # Stop and remove the old container if it exists
        docker stop orv_container || true
        docker rm orv_container || true
        # Run the new container with the specified volume mounts
        docker run -d --name orv_container \
          -p 3000:3000 \
          -v app_photos:/app/photos \
          -v app_videos:/app/videos \
          ${{ secrets.DOCKER_USERNAME }}/orv:${{ github.sha }}

        # Optional: Clean up - remove unused Docker images
        docker image prune -af